### ISSUE TITLE
Feature: Titlepage & TOC support

### ISSUE THREAD

**Issue by cooltrooper** [zhaoterryy/mkdocs-pdf-export-plugin#12]
Hi there,

Would it be possible to generate a single PDF file, with a title page & TOC based on the site. Similar to the ReadTheDocs PDF automatic generation.

I believe this would curretly be possible if the entire documentation was a single page?
It seems it could be as simple as combining the generated PDF's and generating a TOC page?

**Comment by shauser** [comment]
This was outside of the original goal of the project, but it does sound like it could be a nice addition for 1.0. I'm not sure when / if I'll find time to implement this however...

**Comment by lukasreussner** [comment]
Title page & TOC support would be a great feature in combination with a merged PDF of all subpages (including page number). This would make MkDocs a nearly perfect single-source documentation tool (at least for HTML and PDF). Great work @shauser!

**Comment by shauser** [comment]
Merged pdf support was introduced in v0.4.

**Comment by zhaoterryy** [comment]
Instead of having title page & toc support I think it's better (more customizable for the user and easier for me) to create an API for modifying the output.

Closing in favor of #35.
