### ISSUE TITLE
External Markdown Links are pointing to physical location of HTML

### ISSUE THREAD

**Issue by sebastienlevert** [zhaoterryy/mkdocs-pdf-export-plugin#28]
I'm currently using 0.5.0 and I'm having an issue with the PDF generation of a pretty large documentation base. We are using a lot of internal links between our documentation pages and sections and we're seeing something new in our PDF generated file (We are almost certain that this works, at some point...).

When using a link like the following in our documentation `[Topic](topic.md)`, this works nicely in our website but produces a link to the physical generated file (file:///Users/vsts/agent/2.144.0/work/1/s/site/topic/). It does that in our CI/CD environment and does it also in all our local builds.

Anything we should change to make sure the links are clickable through the PDF document?

Thanks!

**Comment by zhaoterryy** [comment]
I'm certain the links were working at some point. I probably.. broke something. 

Can you confirm if 0.3.0/0.4.0 had this working?

**Comment by zhaoterryy** [comment]
I'm mistaken, this was never working.

Naturally would expect these links to point to the appropriate sections and PDFs so I'll aim to fix this for the next release.

**Comment by zhaoterryy** [comment]
Relevant part of [WeasyPrint docs](https://weasyprint.readthedocs.io/en/stable/features.html#pdf):

> They can be either internal, to another part of the same document (eg. `<a href="#pdf">`) or external, to an URL. **External links are resolved to absolute URLs: `<a href="/news/">` on the WeasyPrint website would always point to http://weasyprint.org/news/ in PDF files.**

Still investigating - could be a missing upstream feature.

**Comment by zhaoterryy** [comment]
Upstream issue: https://github.com/Kozea/WeasyPrint/issues/772

**Comment by zhaoterryy** [comment]
You can test the fix by installing v0.5.1b0 -

`pip3 install mkdocs-pdf-export-plugin==0.5.1b0`

**Comment by sebastienlevert** [comment]
Currently, the images seem to be having issues with the latest beta version.

![image](https://user-images.githubusercontent.com/7620955/51688933-97f4d700-1fc3-11e9-80db-6341637c2128.png)

**Comment by zhaoterryy** [comment]
Fixed in v0.5.1b1!

**Comment by sebastienlevert** [comment]
I am seeing a new behaviour now where links within a document are now broken again with 0.5.2b2. Is there any specific format we should use for our links within the HTML that would be picked up when generated in PDF? I'm currently using the following : 

`[title of the article](../folder/article.md).`

The result is that I'm seeing is a link to an relative link like an URL instead of an anchor withint the PDF document : 

![image](https://user-images.githubusercontent.com/7620955/52476049-6d7e4e80-2b6b-11e9-8533-ab3da00828bc.png)

Thanks!
