### ISSUE TITLE
When using combined PDF, the page number are restarted for every article

### ISSUE THREAD

**Issue by sebastienlevert** [zhaoterryy/mkdocs-pdf-export-plugin#29]
We love the new page order as it respects nicely our nav structure, but we're seeing issues with the current page numbers. Page numbers are restarting for every section as it's probably considered to be multiple documents and page numbers are defined per document.

Anything we can do to do the opposite, where if I have 201 pages, I should see Page 1 of 201, 2 of 201, etc...?

Thanks!

**Comment by zhaoterryy** [comment]
@sebastienlevert Could you confirm v0.5.2b0 works for your docs?

**Comment by sebastienlevert** [comment]
It looks like it's working on my end! Thanks for taking the time to debug this one! It means a lot to us! Cheers!

**Comment by CaptainQuirk** [comment]
Hi,

Thanks for the fix ! I was using the following construct to display the page number relative to the total : 

```
      @bottom-right {
          content: counter(page) ' / ' counter(pages);
```

I replaced the `counter(page)` with `counter(__pgnum__)`; But `counter(pages)` is always `1`

**Comment by majkinetor** [comment]
`pages` works for me on single PDF. Your exact code works.
