### ISSUE TITLE
Installation Issue!

### ISSUE THREAD

**Issue by mehrad-meraji** [zhaoterryy/mkdocs-pdf-export-plugin#34]
I installed the plugin using `pip install mkdocs-pdf-export-plugin`
Python 3.7.2
```
ERROR   -  Config value: 'plugins'. Error: The "pdf-export" plugin is not installed

Aborted with 1 Configuration Errors!
```

Thank you

**Comment by zhaoterryy** [comment]
Can you verify the output of `pip --version`?

**Comment by mehrad-meraji** [comment]
`pip 19.0.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)`

**Comment by zhaoterryy** [comment]
Verify `pip show mkdocs-pdf-export-plugin` & `pip show mkdocs` have the same location?

Other than that I'm not sure. Seems like a configuration issue.
