### ISSUE TITLE
Indenting

### ISSUE THREAD

**Issue by franklin-feingold** [zhaoterryy/mkdocs-pdf-export-plugin#37]
Hi,

Thank you for making this great tool! I am running into an issue that the indenting from my md file is not rendering properly in the pdf version. The indents render properly in my md file. Any thoughts are much appreciated! 

Thank you!

**Comment by zhaoterryy** [comment]
Could you give me an example? 

I.e. page number in https://github.com/franklin-feingold/bids-specification/blob/c80bb73cb5c9ca07ad8ef8ed4f045aa54eb73829/BIDS-Specification_v1.1.2.pdf and the corresponding `.md`/`.html`?

> Thank you for making this great tool!

🙇

**Comment by franklin-feingold** [comment]
Thank you for quick reply! 

I just committed the [md](https://github.com/franklin-feingold/bids-specification/blob/pdf_spac/01-introduction_TOC.md) and [html](https://github.com/franklin-feingold/bids-specification/blob/pdf_spac/01-introduction_TOC.html) for the pdf you identified. The page number is the first page, this concerns the indenting of the TOC from the first page. From what I can tell https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/issues/35 could solve this issue

**Comment by zhaoterryy** [comment]
From https://python-markdown.github.io/#differences:

> ... when a list item consists of multiple paragraphs, “each subsequent paragraph in a list item must be indented by either 4 spaces or one tab” (emphasis added). 
... must always be indented by at least four spaces (or one tab) for each level of nesting.

Can you try making sure your indentations are 4 spaces in the `.md` file and report back?

**Comment by franklin-feingold** [comment]
Sorry for the late response - It appears that was the issue, thank you! It should work now
