### ISSUE TITLE
PDF relative links seem to be broken

### ISSUE THREAD

**Issue by CaptainQuirk** [zhaoterryy/mkdocs-pdf-export-plugin#42]
Hi,

I have the following mkdocs structure : 

```
nav:  
  - Accueil: index.md 
  - Users stories:
    - Communiqué de presse:
      - Consulter les communiqués: cp/show.md
  - Glossaire: glossaire.md
```

In `cp/show.md` file, I have the following content : 

```
En tant que [Charge de communication](../glossaire.md#charge-de-communication)
```

It seems to follow what is stated in the **mkdocs** documentation about [links](https://www.mkdocs.org/user-guide/writing-your-docs/#linking-to-pages)

When I launch `mkdocs` I get the following error : 

```
ERROR: No anchor #cp/show/:charge-de-communication for internal URI reference
```

Do you know what is happening ?

Thanks in advance

**Comment by zhaoterryy** [comment]
Fixed in v0.5.3.
