### ISSUE TITLE
Improve README to explain how to use a custom stylesheet

### ISSUE THREAD

**Issue by RacingTadpole** [zhaoterryy/mkdocs-pdf-export-plugin#51]
Thanks for a great tool!

When I use it on the default mkdocs theme, I get lots of blank pages and spurious "Documentation built with MkDocs" footers.  So I thought to try adding a custom stylesheet.

In the README, when you say "The resulting PDF can be customized easily by adding a custom stylesheet such as the following...", can you explain what that means? Where should I put that stylesheet and how do I hook it up?

**Comment by mpilking** [comment]
I had the same problem.  Finally figured it out.  This helped:  https://www.mkdocs.org/user-guide/configuration/#extra_css.  After creating docs/css/extra.css and updating the mkdocs.yml file to include the `extra_css` config, it worked well.   I will submit a PR to update this documentation for newbies like myself.
