### ISSUE TITLE
Set meaningful filename for combined PDF

### ISSUE THREAD

**Issue by fschrempf** [zhaoterryy/mkdocs-pdf-export-plugin#65]
It would be nice if the filename of the combined output file wouldn't be `combined.pdf` but rather derived from `site_name` or configurable by a separate option. This would help people downloading the docs to get a file with a meaningful name.

**Comment by bvkeersop** [comment]
According to the readme this is already possible.
You can add combined_output_path as an option to the pdf-export plugin.

See [here](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin#options).

**Comment by fschrempf** [comment]
> According to the readme this is already possible.
> You can add combined_output_path as an option to the pdf-export plugin.
> 
> See [here](https://github.com/zhaoterryy/mkdocs-pdf-export-plugin#options).

You are perfectly right. The option already exists and works just fine. I somehow missed it when I was looking for it. Thanks!
