### ISSUE TITLE
module 'mkdocs.utils' has no attribute 'string_types'

### ISSUE THREAD

**Issue by timvink** [zhaoterryy/mkdocs-pdf-export-plugin#76]
I am running the new `mkdocs==1.1` which was released 23rd of Feb and `mkdocs-pdf-export-plugin==0.5.5`, but now get the following error:

```
AttributeError: module 'mkdocs.utils' has no attribute 'string_types'
```

This has already been fixed in https://github.com/zhaoterryy/mkdocs-pdf-export-plugin/issues/72, but not released yet. 

Can we do a small hotfix release ? 😄 

**Update**: For those running into this problem, you can run an older version of mkdocss with `pip install mkdocs==1.0.4`, and/or add `mkdocs==1.0.4` to your `requirements.txt`

**Comment by zoni** [comment]
@zhaoterryy any chance you could tag a new version and do a release on PyPI for this please?

**Comment by sgomez** [comment]
@zoni you can add this into your `requirements.txt`

```
git+https://github.com/zhaoterryy/mkdocs-pdf-export-plugin.git@master
```
