### ISSUE TITLE
Bad download icon with material theme 

### ISSUE THREAD

**Issue by majkinetor** [zhaoterryy/mkdocs-pdf-export-plugin#83]
With latest [master and latest material 5.1](https://github.com/majkinetor/mm-docs/blob/master/requirements.txt) icon is not shown correctly any more as download arrow but as ``:

See build here: https://majkinetor.github.io/mm-docs-template:

![image](https://user-images.githubusercontent.com/85767/78900451-26456380-7a77-11ea-919f-6a07dfc3f1f7.png)

**Comment by timvink** [comment]
I had the same issue, managed to fix it in #84:

![image](https://user-images.githubusercontent.com/5570380/79969093-4cb0c900-8491-11ea-885f-6d347499b832.png)
