### ISSUE TITLE
first page is blank

### ISSUE THREAD

**Issue by t-f-x** [zhaoterryy/mkdocs-pdf-export-plugin#87]
hello, 
I am using your plugin with the theme material and the first page is blank (only footer are printed).
I have tried with the theme mkdocs and there is no blank page.
Is it normal ?
how to personalize this page  ?
material : 5.2.2
pdf-export : 0.5.6
python : 3.5.2

**Comment by t-f-x** [comment]
this is a problem of CSS injected by the pdf theme

**Comment by Kanaduchi** [comment]
I have the same issue. What was the problem in CSS?

**Comment by t-f-x** [comment]
the problem is on the file mkdocs_pdf_export_plugin/themes/material.py that inject CSS.
you need to remove the .md-main__inner property because this element insert a blank page. 
after that, you need to have several properties to adjust page layout (like describe on the README.md).
if you need a 'first page' with the name of the document for example, you must insert a @page first properties on the CSS.

**Comment by Kanaduchi** [comment]
Thank you! It helps me!

**Comment by pohlt** [comment]
I fixed this issue by adding
```css
.md-main__inner {
    height: 0% !important;
}
```
to `style.css` which I added as an `extra_css` in `mkdocs.yml`.
